"""restore name no constraint workouts

Revision ID: 191c87e230f1
Revises: 7e20aeda1eca
Create Date: 2023-11-22 21:04:25.021134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191c87e230f1'
down_revision = '7e20aeda1eca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
